using Serenity.Navigation;
using MyPages = CloudGarage.Masters.Pages;

[assembly: NavigationMenu(1020, "Masters", icon: "fa fa-asterisk")]
[assembly: NavigationLink(int.MaxValue, "Masters/Countries", typeof(MyPages.CountriesController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Masters/States", typeof(MyPages.StatesController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Masters/Cities", typeof(MyPages.CitiesController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Masters/Banks", typeof(MyPages.BanksController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Masters/Expenses Types", typeof(MyPages.ExpensestypesController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Masters/Regions", typeof(MyPages.RegionsController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Masters/Territories", typeof(MyPages.TerritoriesController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Masters/Shippers", typeof(MyPages.ShippersController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Masters/Warehouses", typeof(MyPages.WarehousesController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Masters/Customer Groups", typeof(MyPages.CustomergroupsController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Masters/Supplier Groups", typeof(MyPages.SuppliergroupsController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Masters/Agenda Item Types", typeof(MyPages.AgendaitemtypesController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Masters/Meeting Types", typeof(MyPages.MeetingtypesController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Masters/Locations", typeof(MyPages.LocationsController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Masters/Attendance Statuses", typeof(MyPages.AttendancestatusesController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Masters/Attendee Types", typeof(MyPages.AttendeetypesController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Masters/Resolution Statuses", typeof(MyPages.ResolutionstatusesController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Masters/Job Categories", typeof(MyPages.JobcategoriesController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Masters/Job Types", typeof(MyPages.JobtypesController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Masters/Vehicle Types", typeof(MyPages.VehicletypesController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Masters/Color Types", typeof(MyPages.ColortypesController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Masters/Fuel Types", typeof(MyPages.FueltypesController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Masters/Vehicle Makes", typeof(MyPages.VehiclemakesController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Masters/Assembly Types", typeof(MyPages.AssemblytypesController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Masters/Vehicle Models", typeof(MyPages.VehiclemodelsController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Masters/Branches", typeof(MyPages.BranchesController), icon: null)]